#Mass Run Config \u2013 generated 2026-05-17T16:33:33.796164900Z
#Sun May 17 18:33:33 CEST 2026
algorithms=TaxiAlgorithmP2PCollector,TaxiAlgorithmSinglePassenger,TaxiAlgorithmVehicleRouting
baseSeed=116264426
clientCounts=25,25,50,50,100
clientSpawnWindow=5000
clientSpeed=5
idleCheckThrottleTicks=5
idleRoamingEnabled=true
idleRoamingStrategy=page-rank
idleThresholdTicks=60
kHops=0,1,2,5
mapSize=40000
outputDir=mass-run-results
overlayMaxNeighbors=4
overlayMinNeighbors=1
overlayShortcuts=1
p2pStrategies=nearest,greedy
randomTravelMaxDistanceMeters=20000
rqsRadius=1000,5000,10000,20000
runs=10
simulationSpeed=100
spawnScenarios=BASELINE,SPATIAL_IMBALANCE,SPATIAL_ISLANDS
taxiCounts=5,10,10,20,20
taxiSeatCounts=1
taxiSpeed=80
