#Mass Run Config - generated 2026-07-19T04:38:13.855183778Z
#Sun Jul 19 06:38:13 CEST 2026
algorithms=TaxiAlgorithmP2PCollector,TaxiAlgorithmSinglePassenger
baseSeed=0
clientCounts=638,27762
clientSpawnWindow=86400
clientSpeed=5
idleCheckThrottleTicks=15
idleRoamingModes=none,random,past-avg,past-avg-total,past-avg-revisit
idleThresholdTicks=60
kHops=0,1,2
mapSize=7360,29850
outputDir=mass-run-results_11.07-konstanz-berlin
overlayMaxDistanceFactor=1
overlayMaxNeighbors=4
overlayMinNeighbors=0,1
overlayShortcuts=0,1
p2pStrategies=nearest,greedy
parallelWorkers=20
randomTravelMaxDistanceMeters=4000
requestHeatmapZones=20
requestRepublishTicks=15
rqsRadius=1000,2000,3000
runs=10
seenClientTtlTicks=1000
simulationSpeed=100
spawnScenarios=BASELINE,RUSH_HOUR,SPATIAL_IMBALANCE,SPATIAL_ISLANDS
taxiCounts=39,1685
taxiSeatCounts=1
taxiSpeed=30
timeSeriesBucketTicks=1000
topologyScanTicks=2000
