#Mass Run Config \u2013 generated 2026-05-26T11:47:42.155202600Z
#Tue May 26 13:47:42 CEST 2026
algorithms=TaxiAlgorithmP2PCollector,TaxiAlgorithmSinglePassenger,TaxiAlgorithmVehicleRouting
baseSeed=116264426
clientCounts=800
clientSpawnWindow=40000
clientSpeed=5
idleCheckThrottleTicks=10
idleRoamingEnabled=true
idleRoamingModes=none,return-to-hq,past-avg
idleRoamingStrategy=return-to-hq
idleThresholdTicks=60
kHops=0,1
mapSize=10000
outputDir=mass-run-results_26.05.zurich-scaled-down
overlayMaxNeighbors=4
overlayMinNeighbors=1
overlayShortcuts=0,1
p2pStrategies=nearest
randomTravelMaxDistanceMeters=2000
rqsRadius=1000,2000
runs=1
simulationSpeed=100
spawnScenarios=BASELINE,RUSH_HOUR,SPATIAL_IMBALANCE,SPATIAL_ISLANDS
taxiCounts=60
taxiSeatCounts=1
taxiSpeed=80
