#Mass Run Config \u2013 generated 2026-06-27T18:53:21.826786835Z
#Sat Jun 27 20:53:21 CEST 2026
algorithms=TaxiAlgorithmP2PCollector,TaxiAlgorithmSinglePassenger
baseSeed=112351613
clientCounts=638,27762
clientSpawnWindow=86400
clientSpeed=5
idleCheckThrottleTicks=15
idleRoamingEnabled=true
idleRoamingModes=none,random,past-avg,past-avg-total,past-avg-revisit
idleRoamingStrategy=random
idleThresholdTicks=60
kHops=0,1,2
mapSize=7360,29850
outputDir=mass-run-results_17.06-konstanz-berlin
overlayMaxDistanceFactor=1
overlayMaxNeighbors=4
overlayMinNeighbors=1
overlayShortcuts=0,1
p2pStrategies=nearest,greedy
randomTravelMaxDistanceMeters=4000
requestRepublishTicks=15
rqsRadius=1000,2000,3000
runs=4
seenClientTtlTicks=1000
simulationSpeed=100
spawnScenarios=BASELINE,RUSH_HOUR,SPATIAL_IMBALANCE,SPATIAL_ISLANDS
taxiCounts=39,1685
taxiSeatCounts=1
taxiSpeed=30
topologyScanTicks=200
