#Mass Run Config \u2013 generated 2026-06-05T02:12:29.742667600Z
#Fri Jun 05 04:12:29 CEST 2026
algorithms=TaxiAlgorithmP2PCollector,TaxiAlgorithmSinglePassenger,TaxiAlgorithmVehicleRouting
baseSeed=218375489
clientCounts=800,8000,30000
clientSpawnWindow=40000
clientSpeed=5
idleCheckThrottleTicks=10
idleRoamingEnabled=true
idleRoamingModes=past-avg
idleRoamingStrategy=past-avg
idleThresholdTicks=60
kHops=0,1
mapSize=10000,10000,30000
outputDir=mass-run-results_04.06.all
overlayMaxDistanceFactor=1
overlayMaxNeighbors=4
overlayMinNeighbors=1
overlayShortcuts=0
p2pStrategies=nearest
randomTravelMaxDistanceMeters=5000
requestRepublishTicks=12
rqsRadius=1000,2000
runs=1
simulationSpeed=100
spawnScenarios=BASELINE,RUSH_HOUR,SPATIAL_IMBALANCE,SPATIAL_ISLANDS
taxiCounts=60,600,2750
taxiSeatCounts=1
taxiSpeed=80
topologyScanTicks=50
