#Mass Run Config \u2013 generated 2026-05-19T10:02:35.758519400Z
#Tue May 19 12:02:35 CEST 2026
algorithms=TaxiAlgorithmP2PCollector,TaxiAlgorithmSinglePassenger,TaxiAlgorithmVehicleRouting
baseSeed=116264426
clientCounts=80
clientSpawnWindow=4000
clientSpeed=5
idleCheckThrottleTicks=5
idleRoamingEnabled=false
idleRoamingModes=none,return-to-hq
idleRoamingStrategy=random
idleThresholdTicks=60
kHops=0,1,2
mapSize=1000
outputDir=mass-run-results_19.05.large-konstanz-scaled-down
overlayMaxNeighbors=4
overlayMinNeighbors=1
overlayShortcuts=0,1
p2pStrategies=nearest
randomTravelMaxDistanceMeters=2000
rqsRadius=100,200
runs=10
simulationSpeed=100
spawnScenarios=BASELINE,RUSH_HOUR,SPATIAL_IMBALANCE,SPATIAL_ISLANDS
taxiCounts=6
taxiSeatCounts=1
taxiSpeed=80
