#Mass Run Config \u2013 generated 2026-05-07T14:31:27.796612300Z
#Thu May 07 16:31:27 CEST 2026
algorithms=TaxiAlgorithmP2PCollector,TaxiAlgorithmVehicleRouting
baseSeed=1231541341
clientCounts=25,50
clientSpawnWindow=10000
clientSpeed=5
idleCheckThrottleTicks=5
idleRoamingEnabled=true
idleThresholdTicks=20
kHops=0
mapSize=40000
outputDir=mass-run-results
overlayMaxNeighbors=4
overlayMinNeighbors=1
overlayShortcuts=1
p2pStrategies=nearest
randomTravelMaxDistanceMeters=20000
rqsRadius=5000,10000
runs=4
simulationSpeed=100
spawnScenarios=BASELINE,SPATIAL_IMBALANCE
taxiCounts=5,10
taxiSeatCounts=1
taxiSpeed=80
